### ISSUE TITLE
change title bar to this

### ISSUE THREAD

**Issue by stuartcrobinson** [newspass/newspass-website#5]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/12928716/64038009-059e4e00-cb25-11e9-8acd-d089cf8dc35e.png">

let's put the Contact Us tool in the About page

**Comment by stuartcrobinson** [comment]
i'm using https://venmo.com/ for inspiration btw

**Comment by AhmedMKamal** [comment]
Done
